### ISSUE TITLE
Unity 5.5

### ISSUE THREAD

**Issue by Dyoxx** [SlightlyMad/AtmosphericScattering#2]
First, thank you for your work.
I'm having some problems after upgrading to Unity 5.5 (was on 5.4.2)
Skybox appear to be darker depending of the camera Far distance.
Skybox appear brighter around Cutout shaders
https://s23.postimg.org/3y9l4wcob/Horizon55_2017_01_11_06_37_45_39.jpg

**Comment by SlightlyMad** [comment]
Noted. I'll take a look when I have time.
