### ISSUE TITLE
Screen becomes black in 5.5.0f3

### ISSUE THREAD

**Issue by ErickXavier** [SlightlyMad/AtmosphericScattering#3]
Hi, the screen becomes full black (even the sample test scenes) in the 5.5.0f3 version.

Here are the errors that appears on the console:
https://www.dropbox.com/s/si4tizks6dlyyg0/Screenshot%202017-01-26%2011.30.40.png?dl=0

Would love to have this working good on the current versions, could this be possible, pleeeease? :)))

**Comment by maxzoech** [comment]
As far as I know, you need Shader Model 5.0 which doesn’t work on Mac right now. Wait for Metal Support coming in March or grab the Unity 5.6 Beta.

**Comment by SlightlyMad** [comment]
@Max978 is completely right. OpenGL on MacOS doesn't support compute shaders. 5.6 beta might work but it is untested. Closing issue...
