### ISSUE TITLE
Shader not compatible with Metal on macOS

### ISSUE THREAD

**Issue by maxzoech** [SlightlyMad/AtmosphericScattering#5]
Tried the shader today on my MacBook Pro 2015 running Unity 5.6 with Metal. Is there a way to get the shader running on Metal, now that Compute is possible?

**Comment by SlightlyMad** [comment]
It should work. Unfortunately, I don't have a mac anymore. I'll take a look when I get back to work next week...

**Comment by slipster216** [comment]
This can be fixed by changing the return types on the frag functions to float4’s, and fixing the type mismatches in some of the math- the compiler will show all of these errors for you. HLSL tends to be a little looser with type truncation than metal.
